- name: install and run nginx
  hosts: all
  become: yes #-b #become is used to run the task as a superuser
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: ensure nginx is running
      ansible.builtin.command: systemctl status nginx
      register: nginx_status

    